from typing import Protocol
from uuid import UUID


class ConsultasAcademicasRepository(Protocol):
    async def disciplinas(self, busca: str, inicio: int, limite: int) -> list[dict]: ...
    async def turmas(self, codigo: str) -> list[dict]: ...
    async def resumo(self, *, codigo: str | None = None, oferta_id: UUID | None = None) -> dict: ...
    async def matriculas(self, oferta_id: UUID, matricula: str | None) -> list[dict]: ...
